services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
    - ./config:/mosquitto/config
    - ./config:/mosquitto/data
    - ./config:/mosquitto/log
    stdin_open: true
    tty: true

  bot:
    build: .
    container_name: tgbot
    restart: always
    depends_on:
      - mosquitto

volumes:
  config:
  data:
  log:
